CREATE TABLE public.medical_histories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    admited_at timestamp with time zone,
    patient_id integer,
    status text,
    CONSTRAINT pk_medical_histories PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.medical_histories
    OWNER to postgres;

COMMENT ON TABLE public.medical_histories
    IS 'Create medical_histories';

CREATE TABLE public.patients
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text,
    date_of_birth date,
    PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.patients
    OWNER to postgres;

COMMENT ON TABLE public.patients
    IS 'Create patients table.';